/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CollateralChatRouteImport } from './routes/collateral-chat'
import { Route as CollateralTestRouteImport } from './routes/collateral-test'
import { Route as KnowledgeTestRouteImport } from './routes/knowledge-test'
import { Route as LimitsChatRouteImport } from './routes/limits-chat'
import { Route as LimitsTestRouteImport } from './routes/limits-test'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProductsChatRouteImport } from './routes/products-chat'
import { Route as ProductsTestRouteImport } from './routes/products-test'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RatingRouteImport } from './routes/rating'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as TrainersRouteImport } from './routes/trainers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CollateralChatRoute = CollateralChatRouteImport.update({
  id: '/collateral-chat',
  path: '/collateral-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CollateralTestRoute = CollateralTestRouteImport.update({
  id: '/collateral-test',
  path: '/collateral-test',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeTestRoute = KnowledgeTestRouteImport.update({
  id: '/knowledge-test',
  path: '/knowledge-test',
  getParentRoute: () => rootRouteImport,
} as any)
const LimitsChatRoute = LimitsChatRouteImport.update({
  id: '/limits-chat',
  path: '/limits-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const LimitsTestRoute = LimitsTestRouteImport.update({
  id: '/limits-test',
  path: '/limits-test',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsChatRoute = ProductsChatRouteImport.update({
  id: '/products-chat',
  path: '/products-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsTestRoute = ProductsTestRouteImport.update({
  id: '/products-test',
  path: '/products-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingRoute = RatingRouteImport.update({
  id: '/rating',
  path: '/rating',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainersRoute = TrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/collateral-chat': typeof CollateralChatRoute
  '/collateral-test': typeof CollateralTestRoute
  '/knowledge-test': typeof KnowledgeTestRoute
  '/limits-chat': typeof LimitsChatRoute
  '/limits-test': typeof LimitsTestRoute
  '/materials': typeof MaterialsRoute
  '/onboarding': typeof OnboardingRoute
  '/products-chat': typeof ProductsChatRoute
  '/products-test': typeof ProductsTestRoute
  '/profile': typeof ProfileRoute
  '/rating': typeof RatingRoute
  '/tests': typeof TestsRoute
  '/trainers': typeof TrainersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/collateral-chat': typeof CollateralChatRoute
  '/collateral-test': typeof CollateralTestRoute
  '/knowledge-test': typeof KnowledgeTestRoute
  '/limits-chat': typeof LimitsChatRoute
  '/limits-test': typeof LimitsTestRoute
  '/materials': typeof MaterialsRoute
  '/onboarding': typeof OnboardingRoute
  '/products-chat': typeof ProductsChatRoute
  '/products-test': typeof ProductsTestRoute
  '/profile': typeof ProfileRoute
  '/rating': typeof RatingRoute
  '/tests': typeof TestsRoute
  '/trainers': typeof TrainersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/collateral-chat': typeof CollateralChatRoute
  '/collateral-test': typeof CollateralTestRoute
  '/knowledge-test': typeof KnowledgeTestRoute
  '/limits-chat': typeof LimitsChatRoute
  '/limits-test': typeof LimitsTestRoute
  '/materials': typeof MaterialsRoute
  '/onboarding': typeof OnboardingRoute
  '/products-chat': typeof ProductsChatRoute
  '/products-test': typeof ProductsTestRoute
  '/profile': typeof ProfileRoute
  '/rating': typeof RatingRoute
  '/tests': typeof TestsRoute
  '/trainers': typeof TrainersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/chat'
    | '/collateral-chat'
    | '/collateral-test'
    | '/knowledge-test'
    | '/limits-chat'
    | '/limits-test'
    | '/materials'
    | '/onboarding'
    | '/products-chat'
    | '/products-test'
    | '/profile'
    | '/rating'
    | '/tests'
    | '/trainers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/chat'
    | '/collateral-chat'
    | '/collateral-test'
    | '/knowledge-test'
    | '/limits-chat'
    | '/limits-test'
    | '/materials'
    | '/onboarding'
    | '/products-chat'
    | '/products-test'
    | '/profile'
    | '/rating'
    | '/tests'
    | '/trainers'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/chat'
    | '/collateral-chat'
    | '/collateral-test'
    | '/knowledge-test'
    | '/limits-chat'
    | '/limits-test'
    | '/materials'
    | '/onboarding'
    | '/products-chat'
    | '/products-test'
    | '/profile'
    | '/rating'
    | '/tests'
    | '/trainers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  CollateralChatRoute: typeof CollateralChatRoute
  CollateralTestRoute: typeof CollateralTestRoute
  KnowledgeTestRoute: typeof KnowledgeTestRoute
  LimitsChatRoute: typeof LimitsChatRoute
  LimitsTestRoute: typeof LimitsTestRoute
  MaterialsRoute: typeof MaterialsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProductsChatRoute: typeof ProductsChatRoute
  ProductsTestRoute: typeof ProductsTestRoute
  ProfileRoute: typeof ProfileRoute
  RatingRoute: typeof RatingRoute
  TestsRoute: typeof TestsRoute
  TrainersRoute: typeof TrainersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collateral-chat': {
      id: '/collateral-chat'
      path: '/collateral-chat'
      fullPath: '/collateral-chat'
      preLoaderRoute: typeof CollateralChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collateral-test': {
      id: '/collateral-test'
      path: '/collateral-test'
      fullPath: '/collateral-test'
      preLoaderRoute: typeof CollateralTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-test': {
      id: '/knowledge-test'
      path: '/knowledge-test'
      fullPath: '/knowledge-test'
      preLoaderRoute: typeof KnowledgeTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limits-chat': {
      id: '/limits-chat'
      path: '/limits-chat'
      fullPath: '/limits-chat'
      preLoaderRoute: typeof LimitsChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limits-test': {
      id: '/limits-test'
      path: '/limits-test'
      fullPath: '/limits-test'
      preLoaderRoute: typeof LimitsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products-chat': {
      id: '/products-chat'
      path: '/products-chat'
      fullPath: '/products-chat'
      preLoaderRoute: typeof ProductsChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products-test': {
      id: '/products-test'
      path: '/products-test'
      fullPath: '/products-test'
      preLoaderRoute: typeof ProductsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating': {
      id: '/rating'
      path: '/rating'
      fullPath: '/rating'
      preLoaderRoute: typeof RatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainers': {
      id: '/trainers'
      path: '/trainers'
      fullPath: '/trainers'
      preLoaderRoute: typeof TrainersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  CollateralChatRoute: CollateralChatRoute,
  CollateralTestRoute: CollateralTestRoute,
  KnowledgeTestRoute: KnowledgeTestRoute,
  LimitsChatRoute: LimitsChatRoute,
  LimitsTestRoute: LimitsTestRoute,
  MaterialsRoute: MaterialsRoute,
  OnboardingRoute: OnboardingRoute,
  ProductsChatRoute: ProductsChatRoute,
  ProductsTestRoute: ProductsTestRoute,
  ProfileRoute: ProfileRoute,
  RatingRoute: RatingRoute,
  TestsRoute: TestsRoute,
  TrainersRoute: TrainersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
